spring.application.name=ecom
server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ecom?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ok

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.password=ok
spring.data.redis.timeout=5s

app.jwt.secret=change-me-to-a-long-english-only-secret-key-for-demo-project-2026
app.jwt.expiration=86400000
app.redis.product-ttl=30m
app.redis.token-prefix=auth:token:
app.redis.product-prefix=product:
app.redis.cart-prefix=cart:user:
app.redis.popular-key=products:popular

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
