spring.datasource.url=${ECOM_DATASOURCE_URL:jdbc:mysql://mysql:3306/ecom_enterprise?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${ECOM_DATASOURCE_USERNAME:ecom}
spring.datasource.password=${ECOM_DATASOURCE_PASSWORD:ecom}

spring.data.redis.host=${ECOM_REDIS_HOST:redis}
spring.data.redis.port=${ECOM_REDIS_PORT:6379}
spring.data.redis.password=${ECOM_REDIS_PASSWORD:ecom-redis}
