spring.application.name=ecom
spring.profiles.default=dev
server.port=8080
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=true

app.jwt.secret=change-me-to-a-long-english-only-secret-key-for-demo-project-2026
app.jwt.expiration=86400000
app.order.default-tax-rate=0.00
app.order.default-shipping-fee=0.00
app.seed.product-master-resource=seed-data/product-master-100.csv
app.integrations.payment-callback-token=${PAYMENT_CALLBACK_TOKEN:local-payment-callback-token}
app.redis.product-ttl=30m
app.redis.token-prefix=auth:token:
app.redis.product-prefix=product:detail:
app.redis.cart-prefix=cart:user:
app.redis.popular-key=product:popular

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
