spring.datasource.url=${ECOM_DATASOURCE_URL:jdbc:mysql://mysql:3306/ecom_enterprise?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${ECOM_DATASOURCE_USERNAME:ecom}
spring.datasource.password=${ECOM_DATASOURCE_PASSWORD:ecom}

spring.data.redis.host=${ECOM_REDIS_HOST:redis}
spring.data.redis.port=${ECOM_REDIS_PORT:6379}
spring.data.redis.password=${ECOM_REDIS_PASSWORD:ecom-redis}
spring.kafka.bootstrap-servers=${ECOM_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.rabbitmq.host=${ECOM_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${ECOM_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${ECOM_RABBITMQ_USERNAME:ecom}
spring.rabbitmq.password=${ECOM_RABBITMQ_PASSWORD:ecom-rabbit}
app.stripe.enabled=${ECOM_STRIPE_ENABLED:false}
app.stripe.secret-key=${ECOM_STRIPE_SECRET_KEY:}
app.stripe.webhook-secret=${ECOM_STRIPE_WEBHOOK_SECRET:}
app.stripe.currency=${ECOM_STRIPE_CURRENCY:cad}
app.stripe.default-test-payment-method=${ECOM_STRIPE_DEFAULT_TEST_PAYMENT_METHOD:pm_card_visa}
