package com.eason.ecom.messaging;

public enum OrderEventType {
    ORDER_CREATED,
    ORDER_STATUS_CHANGED,
    PAYMENT_INITIATED,
    PAYMENT_UPDATED,
    SHIPMENT_CREATED,
    SHIPMENT_DELIVERED,
    REFUND_REQUEST_CREATED,
    REFUND_REQUEST_REVIEWED,
    REFUND_SETTLED
}
